### ISSUE TITLE
Rake with style check aborted

### ISSUE THREAD

**Issue by DimitriSteyaert** [mschuchard/puppet-check#2]
Hi, first of all a big thank you for this very useful gem. I have used this within my environment but I get an error trying to perform a puppetcheck with style checks enabled.

When I run `rake puppetcheck:file` I get the following error:
```
rake aborted!
LoadError: cannot load such file -- reek
```
While I do have the reek gem installed.
This is the content of my Rakefile:
```
require 'puppet-check/tasks'
PuppetCheck.style_check = true
```
ruby: 2.1.8
puppet-check: 1.1.0
puppet-lint: 1.1.0
reek: 4.0.3

This problem doesn't occur when I run `puppet-check -s .`

Any idea on how to solve this?

**Comment by DimitriSteyaert** [comment]
Ok this seems to be solved now. The only actions I performed were:
- gem cleanup rake (which did nothing)
- gem cleanup json (which did nothing)
- updated bundler from 1.11.2 to 1.12.4 and cleanup bundler to remove 1.11.2

And now my problem is gone.

**Comment by mschuchard** [comment]
Thanks for figuring this out. I actually never use `bundler` so I would not have been able to help here.
